#include <catch2/internal/catch_errno_guard.hpp>